version: '3.7'
services:
  react:
    container_name: rkt-react
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - '/app/node_modules'
      - './front:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
     - "3000:3000"
    links:
     - "flask"

  flask:
    container_name: rkt-flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports: 
     - "5000:5000"
    links: 
     - "postgres"

  postgres:
    container_name: rkt-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: {}
