FROM python:3.9-alpine

WORKDIR /usr/src/app

RUN pip install flask-restful
RUN pip install psycopg2-binary
RUN pip install flask_api
RUN pip install flask-cors
RUN pip install pyjwt
RUN pip install bcrypt
RUN pip install google-auth

COPY back/src/ /usr/src/app/

CMD ["python", "minimal.py"]