FROM node:18-alpine
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY front/package.json ./
COPY front/package-lock.json ./

RUN npm install --silent
RUN npm install react-scripts@5.0.1 -g --silent
RUN npm install nodemon --save-dev

CMD ["nodemon", "--exec", "npm", "start"]